### ISSUE TITLE
Add Optional FIeld Next to Author's Name

### ISSUE THREAD

**Issue by Safnaj** [Bawanthathilan/cardIt#3]
- Some user's might want to show the designation, or writer for a publication under their name.
- Can make a optional field next to Author's name.

![Screenshot 2024-11-23 at 1 23 03 AM](https://github.com/user-attachments/assets/e2b941e3-af94-4ccb-be7b-eb4febfa6364)

**Comment by Bawanthathilan** [comment]
completed
